# Generated by Django 2.2 on 2019-05-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('5', '5 IN'), ('6', '6 IN'), ('7', '7 IN'), ('8', '8 IN'), ('9', '9 IN'), ('10', '10 IN'), ('11', '11 IN')], max_length=2)),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('child_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='childproduct.ChildProduct')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
                'ordering': ['-timestamp'],
            },
        ),
    ]
