# Generated by Django 2.2 on 2019-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childproduct', '0002_auto_20190521_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
